version: 1.0.{build} 
os: Visual Studio 2015 RC 
install:
 - dnvm upgrade
 - npm install gulp bower -global
build_script:
 - npm install
 - gulp build
# artifacts:
#  - path: /bin 
#    name: bin 
# test_script:
#  - gulp test